name: Release

on:
  push:
    tags:
      - "*" # Trigger on any tag

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1

      - name: Build release binary
        run: cargo build --release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary to Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/gol_rs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
