name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Build (release)
        run: cargo build --release --verbose
      - name: Run tests (release)
        run: cargo test --release --verbose
      - name: Upload release binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: gol_rs-release-binary
          path: |
            target/release/gol_rs
            target/release/gol_rs.exe
